import type { AnalysisResult } from "@/lib/types";

export function buildMarkdownReport(result: AnalysisResult, opts: { filename?: string } = {}): string {
  const lines: string[] = [];
  lines.push(`# Resume Quality Analysis`);
  if (opts.filename) lines.push(`Source file: ${opts.filename}`);
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push("");

  lines.push(`## Overall`);
  lines.push(`- Score: ${result.score}/100 (Grade ${result.grade})`);
  lines.push(`- Words: ${result.wordCount.toLocaleString()}`);
  lines.push(`- Bullet points: ${result.bulletCount}`);
  lines.push(`- Estimated pages: ${result.estimatedPages}`);
  lines.push(`- Fixes: ${result.recommendations.length}`);
  if (result.enhanced) {
    lines.push(`- AI wording enhancement: yes${result.enhancedModel ? ` (${result.enhancedModel})` : ""}`);
  }
  lines.push("");

  if (result.enhancedSummary) {
    lines.push(`## AI summary`);
    lines.push(result.enhancedSummary);
    lines.push("");
  }

  if (result.bulletRewrites && result.bulletRewrites.length) {
    lines.push(`## Rewritten bullets (AI)`);
    for (const r of result.bulletRewrites) {
      lines.push(`- Before: ${r.original}`);
      lines.push(`  After:  ${r.rewrite}`);
      if (r.why) lines.push(`  Why:    ${r.why}`);
    }
    lines.push("");
    lines.push(
      `Placeholders like [X%] mark where only you know the real number — never paste a guess.`,
    );
    lines.push("");
  }

  if (result.secondOpinion) {
    const o = result.secondOpinion;
    lines.push(`## Recruiter second opinion (AI)${o.verdict ? ` — ${o.verdict}` : ""}`);
    lines.push(o.summary);
    for (const s of o.strengths) lines.push(`- + ${s}`);
    for (const c of o.concerns) lines.push(`- − ${c}`);
    lines.push("");
    lines.push(`Advisory only — it does not change the score.`);
    lines.push("");
  }

  if (result.warnings.length) {
    lines.push(`## Warnings`);
    for (const w of result.warnings) lines.push(`- ${w}`);
    lines.push("");
  }

  if (result.extractedText) {
    lines.push(`## Extracted text`);
    lines.push("```");
    lines.push(result.extractedText);
    lines.push("```");
    lines.push("");
  }

  lines.push(`## Score breakdown`);
  for (const d of result.dimensions) {
    lines.push(`### ${d.label} — ${d.score}/100 (${d.key})`);
    if (d.summary) lines.push(`- ${d.summary}`);
    if (d.findings.length) {
      lines.push(`- Findings:`);
      for (const f of d.findings) lines.push(`  - ${f}`);
    }
    if (d.recommendations.length) {
      lines.push(`- Recommendations:`);
      for (const r of d.recommendations) lines.push(`  - [${r.priority.toUpperCase()}] ${r.title}`);
    }
    lines.push("");
  }

  if (result.match.provided) {
    lines.push(`## Job description match`);
    lines.push(`- Score: ${result.match.score}%`);
    if (result.match.mustHaveMissing.length || result.match.mustHaveFound.length) {
      lines.push(`- Required & matched (${result.match.mustHaveFound.length}): ${result.match.mustHaveFound.join(", ") || "none"}`);
      lines.push(`- Required but missing (${result.match.mustHaveMissing.length}): ${result.match.mustHaveMissing.join(", ") || "none"}`);
    }
    lines.push(`- Matched (${result.match.keywordsFound.length}): ${result.match.keywordsFound.join(", ") || "none"}`);
    lines.push(`- Missing (${result.match.keywordsMissing.length}): ${result.match.keywordsMissing.join(", ") || "none"}`);
    if (result.match.buriedKeywords.length) {
      lines.push(`- Buried after Experience (${result.match.buriedKeywords.length}): ${result.match.buriedKeywords.join(", ")}`);
    }
    if (result.match.recommendations.length) {
      lines.push(`- Recommendations:`);
      for (const r of result.match.recommendations) lines.push(`  - [${r.priority.toUpperCase()}] ${r.title}`);
    }
    lines.push("");
  }

  lines.push(`## All recommendations (priority order)`);
  if (result.recommendations.length === 0) {
    lines.push(`- No issues found — the resume looks solid.`);
  } else {
    for (const r of result.recommendations) {
      lines.push(`### ${r.title} [${r.priority.toUpperCase()}] (${r.dimension})`);
      lines.push(`- Why: ${r.why}`);
      lines.push(`- Fix: ${r.fix}`);
      lines.push("");
    }
  }

  lines.push(`---\nAnalysis runs server-side and is not stored. This report was generated by the Resume Quality Analyzer.`);
  return lines.join("\n");
}
