import type { AnalysisResult } from "@/lib/types";

export function buildMarkdownReport(result: AnalysisResult, opts: { filename?: string } = {}): string {
  const lines: string[] = [];
  lines.push(`# Resume Quality Analysis`);
  if (opts.filename) lines.push(`Source file: ${opts.filename}`);
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push("");

  lines.push(`## Overall`);
  lines.push(`- Score: ${result.score}/100 (Grade ${result.grade})`);
  lines.push(`- Words: ${result.wordCount.toLocaleString()}`);
  lines.push(`- Bullet points: ${result.bulletCount}`);
  lines.push(`- Estimated pages: ${result.estimatedPages}`);
  lines.push(`- Fixes: ${result.recommendations.length}`);
  lines.push("");

  if (result.warnings.length) {
    lines.push(`## Warnings`);
    for (const w of result.warnings) lines.push(`- ${w}`);
    lines.push("");
  }

  lines.push(`## Score breakdown`);
  for (const d of result.dimensions) {
    lines.push(`### ${d.label} — ${d.score}/100 (${d.key})`);
    if (d.summary) lines.push(`- ${d.summary}`);
    if (d.findings.length) {
      lines.push(`- Findings:`);
      for (const f of d.findings) lines.push(`  - ${f}`);
    }
    if (d.recommendations.length) {
      lines.push(`- Recommendations:`);
      for (const r of d.recommendations) lines.push(`  - [${r.priority.toUpperCase()}] ${r.title}`);
    }
    lines.push("");
  }

  if (result.match.provided) {
    lines.push(`## Job description match`);
    lines.push(`- Score: ${result.match.score}%`);
    lines.push(`- Matched (${result.match.keywordsFound.length}): ${result.match.keywordsFound.join(", ") || "none"}`);
    lines.push(`- Missing (${result.match.keywordsMissing.length}): ${result.match.keywordsMissing.join(", ") || "none"}`);
    if (result.match.recommendations.length) {
      lines.push(`- Recommendations:`);
      for (const r of result.match.recommendations) lines.push(`  - [${r.priority.toUpperCase()}] ${r.title}`);
    }
    lines.push("");
  }

  lines.push(`## All recommendations (priority order)`);
  if (result.recommendations.length === 0) {
    lines.push(`- No issues found — the resume looks solid.`);
  } else {
    for (const r of result.recommendations) {
      lines.push(`### ${r.title} [${r.priority.toUpperCase()}] (${r.dimension})`);
      lines.push(`- Why: ${r.why}`);
      lines.push(`- Fix: ${r.fix}`);
      lines.push("");
    }
  }

  lines.push(`---\nAnalysis runs server-side and is not stored. This report was generated by the Resume Quality Analyzer.`);
  return lines.join("\n");
}
