"use client";

import type { SecondOpinion } from "@/lib/types";

/** Verdict → restrained palette that matches the rest of the report. */
const VERDICT_STYLES: Record<string, string> = {
  Strong: "border-[#b7e2c8] bg-[#f0fdf4] text-[#067647]",
  Competitive: "border-[#bcd7f7] bg-[#f2f7ff] text-[#0072f5]",
  "Needs work": "border-[#f2ddc0] bg-[#fff8ed] text-[#b54708]",
  "High risk": "border-[#f6c9c4] bg-[#fdf3f2] text-[#b42318]",
};

/**
 * The AI recruiter "second opinion" — a blunt read of the resume.
 * Explicitly labelled as AI and advisory: it never moves the deterministic score.
 */
export function SecondOpinionCard({
  opinion,
  model,
}: {
  opinion: SecondOpinion;
  model?: string;
}) {
  const verdictClass = opinion.verdict
    ? VERDICT_STYLES[opinion.verdict] ?? VERDICT_STYLES.Competitive
    : null;

  return (
    <div className="rounded-lg border border-[#e6d5f2] bg-[#fbf5ff] p-5">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h2 className="flex items-center gap-2 text-[20px] font-semibold tracking-[-0.96px] text-[#7a3cae]">
          <span aria-hidden className="font-mono text-[15px]">◆</span>
          Recruiter second opinion
        </h2>
        {opinion.verdict && verdictClass && (
          <span
            className={`rounded-full border px-2.5 py-0.5 font-mono text-[10px] font-medium uppercase tracking-[0.06em] ${verdictClass}`}
          >
            {opinion.verdict}
          </span>
        )}
      </div>

      <p className="mt-3 text-[14px] leading-relaxed text-[#4d4d4d]">{opinion.summary}</p>

      <div className="mt-4 grid gap-4 sm:grid-cols-2">
        {opinion.strengths.length > 0 && (
          <div>
            <p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#067647]">
              Strengths
            </p>
            <ul className="mt-1.5 space-y-1">
              {opinion.strengths.map((s, i) => (
                <li key={i} className="flex gap-2 text-[13px] leading-relaxed text-[#4d4d4d]">
                  <span aria-hidden className="font-mono text-[#067647]">+</span>
                  <span>{s}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
        {opinion.concerns.length > 0 && (
          <div>
            <p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#b54708]">
              Concerns
            </p>
            <ul className="mt-1.5 space-y-1">
              {opinion.concerns.map((c, i) => (
                <li key={i} className="flex gap-2 text-[13px] leading-relaxed text-[#4d4d4d]">
                  <span aria-hidden className="font-mono text-[#b54708]">−</span>
                  <span>{c}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      <p className="mt-4 border-t border-[#ecdcf8] pt-3 font-mono text-[11px] text-[#9b6fc4]">
        Advisory only — it does not change your score.
        {model ? ` Generated by ${model}.` : ""}
      </p>
    </div>
  );
}
